export const caseStudies = [
  {slug:'anterior-veneers',category:'aesthetic',categoryLabel:'Aesthetic',units:'8 units',title:'Anterior Lithium Disilicate Veneers',image:'anterior.png',challenge:'Create a brighter, more harmonious smile while preserving healthy tooth structure and the patient’s natural character.',solution:'Eight minimally prepared lithium disilicate veneers were digitally designed, pressed, and individually layered for controlled translucency.',material:'Lithium disilicate',workflow:'Digital scan · Pressed ceramic',turnaround:'7 working days',shade:'BL3 / custom layering'},
  {slug:'full-arch-zirconia',category:'implants',categoryLabel:'Implants',units:'12 units',title:'Single & Full Arch',image:'full-arch.png',challenge:'Restore a fully edentulous arch with stable function, cleansable contours, and natural-looking transition zones.',solution:'A verification-jig workflow and approved PMMA prototype informed a monolithic zirconia final with layered gingival characterization.',material:'Multilayer zirconia',workflow:'Scan bodies · CAD/CAM',turnaround:'10 working days',shade:'A2 / gingival custom'},
  {slug:'posterior-crowns',category:'fixed',categoryLabel:'Fixed',units:'4 units',title:'Interior & Posterior Crown & Bridge',image:'posterior.png',challenge:'Deliver durable posterior restorations with reliable contacts and minimal chairside occlusal adjustment.',solution:'Four monolithic zirconia crowns were designed from a fully digital impression and finished with subtle external staining.',material:'High-translucency zirconia',workflow:'Intraoral scan · Milled',turnaround:'4 working days',shade:'A3'},
  {slug:'digital-denture',category:'removable',categoryLabel:'Removable',units:'Full dentures and partial',title:'Full dentures and partial, orthodontic appliances',image:'denture.png',challenge:'Improve retention, phonetics, and facial support for a long-term denture wearer with an unstable existing prosthesis.',solution:'The approved digital try-in was carried through to a milled base and premium teeth, preserving the verified tooth position.',material:'Milled PMMA base',workflow:'Digital impression · Try-in',turnaround:'8 working days',shade:'A2 / natural gingiva'},
  {slug:'implant-bridge',category:'implants',categoryLabel:'Implants',units:'6 units',title:'Implant-Supported Bridge',image:'implant-bridge.png',challenge:'Replace a posterior span with passive implant fit and a cleansable emergence profile.',solution:'A screw-retained zirconia bridge was milled over a titanium interface and verified on a printed master model.',material:'Zirconia / titanium',workflow:'Scan body · Verification model',turnaround:'8 working days',shade:'A2'},
  {slug:'smile-design',category:'aesthetic',categoryLabel:'Aesthetic',units:'10 units',title:'Veneer Smile Design',image:'smile-design.png',challenge:'Correct proportion and incisal display while keeping the final result soft and age appropriate.',solution:'Facially driven planning, a printed mock-up, and ten hand-finished veneers translated the approved design into ceramic.',material:'Lithium disilicate',workflow:'DSD · Mock-up · Pressed',turnaround:'9 working days',shade:'BL4'},
  {slug:'layered-crowns',category:'fixed',categoryLabel:'Fixed',units:'3 units',title:'Layered Ceramic Crowns',image:'layered-crowns.png',challenge:'Match three anterior crowns to adjacent natural teeth with complex internal character.',solution:'Zirconia frameworks were cut back and layered by hand using clinical photography and a custom shade map.',material:'Layered zirconia',workflow:'Digital design · Hand layer',turnaround:'7 working days',shade:'Custom shade map'},
  {slug:'clear-aligners',category:'orthodontic',categoryLabel:'Orthodontic',units:'24 stages',title:'Clear Aligner Series',image:'aligner.png',challenge:'Resolve mild crowding and improve arch form through a conservative, staged movement plan.',solution:'A 24-stage setup with programmed attachments and two refinement checkpoints supported predictable tracking.',material:'Multilayer aligner foil',workflow:'Scan · Setup · 3D print',turnaround:'6 working days',shade:'Clear'},
  {slug:'maryland-bridge',category:'fixed',categoryLabel:'Fixed',units:'1 pontic',title:'Maryland Bridge Restoration',image:'maryland.png',challenge:'Replace a missing lateral incisor with a conservative solution and discreet palatal retention.',solution:'A single-wing zirconia framework was digitally positioned and layered to blend into the anterior smile line.',material:'Layered zirconia',workflow:'Digital scan · Milled',turnaround:'6 working days',shade:'A1'},
  {slug:'partial-framework',category:'removable',categoryLabel:'Removable',units:'Lower',title:'Cast Partial Framework',image:'partial.png',challenge:'Provide stable bilateral support while maintaining a slim, comfortable lingual profile.',solution:'The cobalt-chrome framework was digitally surveyed, printed in resin, cast, finished, and fit-checked on the master model.',material:'Cobalt chrome',workflow:'Digital survey · Cast',turnaround:'7 working days',shade:'Metal framework'},
  {slug:'feldspathic-veneers',category:'aesthetic',categoryLabel:'Aesthetic',units:'6 units',title:'Feldspathic Layered Veneers',image:'veneers.png',challenge:'Close minor spaces and refine incisal form with the most conservative ceramic thickness possible.',solution:'Six refractory-die feldspathic veneers were layered for enamel-like depth with highly controlled margins.',material:'Feldspathic ceramic',workflow:'Wax-up · Refractory layer',turnaround:'8 working days',shade:'A1 / translucent'},
  {slug:'custom-abutments',category:'implants',categoryLabel:'Implants',units:'2 units',title:'Custom Titanium Abutments',image:'abutments.png',challenge:'Create ideal restorative support where implant angulation compromised the emergence path.',solution:'Two patient-specific titanium abutments were digitally designed with tissue-supporting contours and verified clearances.',material:'Grade 5 titanium',workflow:'Scan body · CAD/CAM',turnaround:'5 working days',shade:'Titanium'}
];

export const findCaseStudy = slug => caseStudies.find(item => item.slug === slug) || caseStudies[0];
